blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/just-mn/calenbar/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/just-mn/calenbar/blob/main/README.md
    about: Read the documentation
